# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.containerName }}-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 4  
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.image.containerName }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.containerName }}
    spec:
      containers:
      - name: {{ .Values.image.containerName }}-container
        # image: "{{ .Values.image.repository }}:{{ .Values.image.tag  }}"
        image: {{ .Values.image.repository }}        ##Harness deployment
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.image.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.containerName }}-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: {{ .Values.image.containerName }}
